runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  GITHUB_TOKEN: "nZszZi3GjtbLxoA9Hj2xAgRe4c1B2L34sNKj"

runtime_config:
  operating_system: ubuntu22
  runtime_version: "3.10"

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

instance_class: F1