# runtime: python310
# handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
# - url: /static
#   static_dir: static

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
# - url: /.*
#   script: auto

# resources:
#   cpu: 2
#   memory_gb: 4
#   disk_size_gb: 20

# instance_class: F4
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  operating_system: ubuntu22
  runtime_version: "3.10"

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

instance_class: F1