name: CD
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  deploy:
    name: Deployment to GCP VMs
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0

    - name: Installing Dependencies
      run: |
        pip3 install --upgrade pip
        pip install firebase-admin
        pip install -r Part2/requirements.txt
        gcloud components install cloud-datastore-emulator beta --quiet

    - name: Deploy to app engine
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: Part2/app.yaml
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials: ${{ secrets.GCP_SA_KEY }}
    
      secretEnv: ['GITHUB_TOKEN']
      availableSecrets:
        secretManager:
        - env: 'GITHUB_TOKEN'
          versionName: 'projects/772186541525/secrets/GITHUB_TOKEN/versions/latest'
