name: Continuous Integration (CI)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: install pep8
        run: pip install flake8
      - name: autopep8
        run: pip install autopep8
      - name: Running Flake8
        run: |
          autopep8 Part2/ --recursive --in-place
          cd Part2/
          flake8 --exclude=ECE_461-1/ --max-line-length=460 --ignore=F401,E501,F841,F405,F403,E999 .
      - name: getting requirements.txt
        run: |
          cd Part2/
          pip install -r requirements.txt
      - name: get ts-jest
        run: | 
          npm install --save-dev jest @types/jest
          npm install -g ts-jest
      - name: get npx
        run: |
          npm install -g npx
      - name: run test suite
        run: |
          cd Part2/Testing/
          npx jest test_apis.test.ts


